Total:
  - "Cut:10:1:3:0" #剪10个羊毛奖励1个水晶3点经验和0个金钱
  - "Craft:1:1:1:1"
  - "Kill:1:1:1:1"
  - "Ench:1:1:1:1"
  - "Tool:1:1:1:1"
  - "Fish:1:1:1:1"
Once:
  1:
    Name: "这是收集草方块任务"
    Items:
      - "GRASS_BLOCK:16" #需要16个草方块
    Reward: "1:3:0" #奖励1个水晶3点经验和0个金钱